# Pre-commit hooks configuration - Simplified for practical use
# See https://pre-commit.com for more information

repos:
  # Python formatting and linting with Ruff (replaces Black + flake8 + isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: mixed-line-ending

  # Configuration file validation
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        exclude: ^(\.github/|docs/|data/)
  # Type checking (essential)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: ^src/

  # Documentation health check (custom)
  - repo: local
    hooks:
      - id: docs-health-check
        name: Documentation Health Check
        entry: python3 docs_framework.py health-check
        language: system
        pass_filenames: false
        stages: [pre-commit]

  # NOTE: Additional CI checks that run on GitHub but not locally:
  # - bandit security scan: runs in CI to catch security issues
  # - pytest tests: runs in CI with full test suite
  # - coverage reports: uploaded to codecov in CI
  #
  # To run these manually before pushing:
  # - Security: pip install bandit && bandit -r src/ -f json
  # - Tests: pip install pytest && pytest tests/ --tb=short
