# Clean Configuration for LONG Precision ≥85% - Weekly Tails Dominant
# Cleaned version removing unnecessary parameters

[data]
symbol = "BNB/USDT"
lookback_days = 500
timeframes = ["1d", "1w"]

[signals]
# Signal weights and thresholds for LONG precision ≥85%
min_confirmations = 1
confidence_threshold = 0.25  # FURTHER REDUCED for testing - will increase later

[signals.weights]
weekly_tails = 0.60  # gate + highest weight
fibonacci = 0.20
trend = 0.10
moving_avg = 0.10
sentiment = 0.00  # disabled for now

[signals.thresholds]
confidence_min = 0.85

# Critical modules that must be healthy for signal generation
critical_modules = ["weekly_tails"]  # Weekly tails is critical for 100% LONG accuracy

[weekly_tails]
# Enhanced parameters for LONG precision ≥85% with correct ATR normalization (TESTING)
lookback_weeks = 8
atr_period = 14
vol_sma_period = 20
min_tail_size = 0.02        # Minimum tail size as percentage of price (2%)
strong_tail_size = 0.05     # Strong tail size threshold (5%)
confluence_bonus = 1.5      # Bonus multiplier for confluence with other levels
min_tail_ratio = 0.3        # lower_wick >= 0.3 * ATR(1W) (LOWERED for testing)
min_tail_strength = 0.35    # tail_strength >= 0.35 (LOWERED further for testing)
min_close_pos = 0.2         # (close - low) / (high - low) >= 0.2 (LOWERED for testing)
max_body_atr = 2.0          # body_size / ATR <= 2.0 (INCREASED for testing)

[fibonacci]
swing_lookback = 100
key_levels = [0.382, 0.618]
proximity_threshold = 0.03
min_swing_size = 0.15

[indicators]
rsi_period = 14
rsi_overbought = 70
rsi_oversold = 30
macd_fast = 8
macd_slow = 17
macd_signal = 9
atr_period = 14
bb_period = 20
bb_std = 2

[trend_analysis]
trend_lookback_days = 30
trend_threshold = 0.015

[risk_management]
stop_loss_enabled = true
position_sizing = true
max_risk_per_trade = 0.02

[sentiment]
# Sentiment analysis configuration
enabled = true
sources = ["fear_greed", "social", "news"]
sentiment_weight = 0.3

[ichimoku]
# Ichimoku Cloud settings
tenkan_period = 9
kijun_period = 26
senkou_span_b = 52

[divergence]
# Divergence detection settings
lookback_period = 20
min_divergence_strength = 0.3

[elliott_wave]
# Elliott Wave analysis settings
enabled = true
wave_degree = "primary"
