[data]
symbol = "BNB/USDT"
lookback_days = 500
timeframes = ["1d", "1w"]

[fibonacci]
swing_lookback = 100
key_levels = [0.382, 0.618]
proximity_threshold = 0.01
min_swing_size = 0.15

[weekly_tails]
lookback_weeks = 8
min_tail_size = 0.03
strong_tail_size = 0.05
confluence_bonus = 1.5
# Нови параметри за по-добра SHORT точност
min_wick_ratio = 3.0
volume_confirmation = true
volume_multiplier = 1.5
# Phase 1.3: Fibonacci resistance check за SHORT сигнали
fibonacci_resistance_check = true
fibonacci_proximity_threshold = 0.02  # Колко близо трябва да е опашката до Fib resistance

[indicators]
rsi_period = 14
rsi_overbought = 80
rsi_oversold = 20
macd_fast = 8
macd_slow = 17
macd_signal = 9
bb_period = 20
bb_std = 2.0
# Volume confirmation за BB rejection
bb_volume_confirmation = true
bb_volume_multiplier = 1.5
bb_volume_lookback = 20
# ATR за volatility analysis
atr_period = 14
atr_multiplier = 2.0

[signals]
fibonacci_weight = 0.35
weekly_tails_weight = 0.35
rsi_weight = 0.15
macd_weight = 0.10
bb_weight = 0.05
min_confirmations = 2
confidence_threshold = 0.7
fib_tail_required = true

# Балансирани параметри за 75%+ точност
trend_filter = true
trend_lookback_days = 30
trend_threshold = 0.015

# Балансирани изисквания за SHORT сигнали
short_signal_requirements = true
short_min_fib_level = 0.5
short_min_tail_strength = 0.6
short_trend_confirmation = true

# Балансирани изисквания за LONG сигнали
long_signal_requirements = true
long_min_fib_level = 0.5
long_min_tail_strength = 0.4
long_trend_confirmation = false

[elliott_wave]
enabled = true
lookback_periods = 50
min_wave_strength = 0.02
confidence_threshold = 60

[whale_tracker]
enabled = true
mega_whale_threshold = 100000
whale_threshold = 50000
large_holder_threshold = 10000
medium_holder_threshold = 1000
volume_spike_threshold = 2.0
price_change_threshold = 0.02

[ichimoku]
enabled = true
tenkan_period = 9
kijun_period = 26
senkou_span_b_period = 52
chikou_span_offset = 26
senkou_span_offset = 26

[sentiment]
enabled = true
fear_greed_weight = 0.3
social_weight = 0.25
news_weight = 0.25
momentum_weight = 0.2
confidence_threshold = 60

[divergence]
enabled = true
min_peak_distance = 5
min_peak_prominence = 0.02
lookback_periods = 20

[moving_averages]
enabled = true
fast_period = 10
slow_period = 50
volume_confirmation = true
volume_multiplier = 1.5
volume_lookback = 14

[price_patterns]
enabled = true
min_pattern_distance = 5
pattern_threshold = 0.02
volume_confirmation = true
candle_confirmation = true

# Phase 1: SHORT Signals Improvements
[short_signals]
enabled = true
trend_filter = true
trend_strength_threshold = 0.3
min_fibonacci_resistance = true
volume_confirmation = true
min_tail_strength = 0.6
burn_filter = false  # Ще се активира след имплементация
price_action_rejection = false  # Ще се активира след имплементация
multi_timeframe_alignment = false  # Ще се активира след имплементация
market_regime_detection = false  # Ще се активира след имплементация
signal_quality_scoring = false  # Ще се активира след имплементация
min_quality_score = 70
confidence_threshold = 0.8

[long_signals]
enabled = true
ema_confirmation = false  # Ще се активира в Phase 2
min_risk_reward = 2.0
burn_enhancement = false  # Ще се активира в Phase 2

[bnb_burn]
enabled = false  # Ще се активира след имплементация
pre_burn_window_days = 14
post_burn_window_days = 7
burn_confidence_bonus = 0.15
burn_target_pct = 0.05

[market_regimes]
strong_bull = "SHORT_DISABLED"
weak_bull = "SHORT_HIGH_CONFIDENCE"
range = "SHORT_ENABLED"
bear = "SHORT_ENABLED"

[price_action]
rejection_wick_multiplier = 2.0
min_rejection_distance = 0.01

# Fibonacci SHORT signal rejection parameters
rejection_threshold = 0.03  # 3% minimum distance for strong rejection

[signal_scoring]
fibonacci_weight = 35
weekly_tails_weight = 30
trend_weight = 20
volume_weight = 10
divergence_weight = 5

[risk_management]
stop_loss_enabled = true
position_sizing = true
max_risk_per_trade = 0.02
